### ISSUE TITLE
[FR] can you add your auto bed leveling probe holder

### ISSUE THREAD

**Issue by deckenventilator24** [DariusV21/MarlinCube_1.1.8#1]
Hello
I've seen that auto bed leveling is activated in your config so I ask you can you add the stl file of the holder to the repository? Would be nice.
Thanks

**Comment by DariusV21** [comment]
Hi, there ya go! 
https://www.thingiverse.com/thing:3400864

Probe that i use:
https://www.aliexpress.com/item/32844213899.html

**Comment by deckenventilator24** [comment]
Hello, it's me again. And I have some questions.
Did you have to burn a bootloader onto your printer or was one already on it?
If you did have to burn a bootloader on it how did you do it (where did you connect the mosi/miso/sck pins to?)
Is your board a Melzi v2.0 Pro too?
Thanks for your help.

**Comment by DariusV21** [comment]
Hello, sorry for the dellay. Is everything all right ?
Did you manage to reflash your printer ?
My board is Melzi V2.0 (don't know about the Pro part)
I am flashing it like an usual arduino board, through Arduino IDE (with
added Sanguino board libraries)

2019-10-26, št, 18:12 Robin Neubig <notifications@github.com> rašė:
